from django.urls import path
from . import views

app_name = 'admin_panel'

urlpatterns = [
    path('admin_panel/', views.admin_panel, name='admin_panel'),
    path('user_profile/', views.user_profile_view, name='user_profile'),
    path('delete_profile/<int:profile_id>/', views.delete_profile, name='delete_profile'),
    path('update_user/<int:user_id>/', views.update_user, name='update_user'),
    path('add_user/', views.add_user, name='add_user'),
    path('categories/', views.category_list, name='category_list'),
    path('delete_category/<int:category_id>/', views.delete_category, name='delete_category'),
    path('update_category/<int:category_id>/', views.update_category, name='update_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('featured-projects/', views.featured_projects, name='featured_projects'),
    path('delete-featured-project/<int:project_id>/', views.delete_featured_project, name='delete_featured_project'),
    path('featured-projects/<int:project_id>/update/', views.update_featured_project, name='update_featured_project'),
    path('add_featured_project/', views.add_featured_project, name='add_featured_project'),
    path('comments/', views.comment_list, name='comment'),
    path('comments/add/', views.add_comment, name='addcomment'),
    path('comments/<int:pk>/update/', views.update_comment, name='updatecomment'),
    path('add_donation/', views.add_donation, name='add_donation'),
    path('update_donation/<int:donation_id>/', views.update_donation, name='update_donation'),
    path('list_donations/', views.list_donations, name='donations'),
    path('add_reply/', views.add_reply, name='add_reply'),
    path('update_reply/<int:reply_id>/', views.update_reply, name='update_reply'),
    path('list_replies/', views.list_replies, name='replies'),
    path('show-tags/', views.show_added_tags, name='show_added_tags'),
    path('add-tag/',views.add_tag, name='add_tag'),
    path('update-tag/<int:tag_id>/',views.update_tag, name='update_tag'),
    path('delete-tag/<int:tag_id>/', views.delete_tag, name='delete_tag'),
    path('rate-project/', views.rate_project, name='rate_project'),
    path('show-rate/', views.show_rate, name='show_rate'),
    path('update-rating/<int:rating_id>/', views.update_rating, name='update_rating'),
    path('delete-rating/<int:rating_id>/', views.delete_rating, name='delete_rating'),
    path('add-report/', views.add_report, name='add_report'),
    path('show-reports/', views.show_reports, name='show_reports'),
    path('update_report/<int:report_id>/', views.update_report, name='update_report'),
    path('delete_report/<int:report_id>/', views.delete_report, name='delete_report'),
    path('projects/', views.project_list_view, name='project'), 
    path('delete_project/<int:project_id>/', views.delete_project, name='delete_project'),
    path('update_project/<int:project_id>/', views.update_project, name='update_project'),
    path('add_project/', views.add_project, name='add_project'),
    path('cancellation/list/', views.cancellation_list, name='cancellation_list'),
    path('update_cancellation/<int:cancellation_id>/', views.update_cancellation, name='update_cancellation'),
    path('cancellation/create/', views.create_cancellation, name='create_cancellation'),
    path('cancellation/<int:cancellation_id>/delete/', views.delete_cancellation, name='delete_cancellation'),
    path('project/pictures/', views.project_picture_list, name='project_picture_list'),
    path('project/pictures/add/', views.add_project_picture, name='add_project_picture'),
    path('project/pictures/<int:picture_id>/update/', views.update_project_picture, name='update_project_picture'),
    path('project/pictures/<int:picture_id>/delete/', views.delete_project_picture, name='delete_project_picture'),

   
]