# Generated by Django 5.0.3 on 2024-04-14 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_project_pictures_projectpicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.AddField(
            model_name='featuredproject',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='tag',
            name='projects',
            field=models.ManyToManyField(related_name='tags', to='project.project'),
        ),
    ]
