# Generated by Django 5.0.3 on 2024-04-16 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_featuredproject_created_at_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
