# Generated by Django 5.0.3 on 2024-04-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
    ]
