# Generated by Django 5.0.3 on 2024-04-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('item_name', models.CharField(max_length=100)),
                ('currency_code', models.CharField(max_length=3)),
                ('invoice', models.CharField(max_length=50)),
                ('custom', models.CharField(max_length=100)),
            ],
        ),
    ]
